### ISSUE TITLE
[Chapter 05] 스트림 병렬 처리에서 내부 상태를 갖는 연산에 대해서

### ISSUE THREAD

**Issue by shkisme** [Java-Spring-Study/modern-java-in-action#5]
> P.175에 콜아웃 형식으로 적혀있는 `스트림 연산 : 상태 없음과 상태 있음` 부분의 글을 읽고 든 의문입니다.

map, filter 등의 내부 상태를 갖지 않는 연산은 병렬 처리 시에도 안전해 보입니다. 하지만 글에서 소개된 **내부 상태를 갖는 연산**(sorted, distinct 등등)은 병렬 처리 시에 사용할 시 뭔가 안전하지 않아 보입니다.

예를 들어, 메뉴를  칼로리 순으로 정렬하고 싶어서 sorted 연산을 사용하려 합니다. 또한 데이터의 양이 무지무지 커서 성능 테스트 등의 검증을 거치고, 병렬 처리를 해야 하는 경우입니다.
```java
menu.parallelStream()
   .map(Dish::getCalories)
   .sorted()
   .collect(toList());
```

> P. 193 쪽 밑 문단을 보면, 다음처럼 적혀있습니다.
> 병렬 코드에서는 발행자에 상태가 있으면 안전하지 않다.

이처럼 내부 상태를 갖는 연산도, 위험해 보이는데 어떻게 정상적인 작동을 하는 걸까요?

**Comment by shkisme** [comment]
흠.. 아래 링크에서 어느정도 답을 찾은 것 같습니다!!

[Java8 Stream의 parallel 처리](https://www.popit.kr/java8-stream%EC%9D%98-parallel-%EC%B2%98%EB%A6%AC/)

> 이와 같은 Stream 파이프라인에서 distinct, sorted 등은 어떻게 병렬로 처리되는 것일까? distinct(), sorted()와 같은 중간 단계 연산들(intermediate operation) 중 일부 연산자들은 연산자 **내부에 상태(State) 정보를 가지고 있다.** 모든 Worker 들은 독립적으로 다른 Thread에 의해 실행되지만 처리 결과를 이런 상태 정보에 저장하고, distinct() 연산자는 이 정보를 이용하여 정해진 기능을 수행한다. 즉, **내부적으로 어떤 공용 변수를 만들어 놓고 각 worker 들이 이 변수에 접근할 경우 동기화 작업(synchronized) 등을 통해 변수를 안전하게 유지하면서 처리**하고 있다. **내부적으로는 기존 Thread 작업 시 개발자가 해줘야 했던 동기화 등의 작업을 모두 수행하고 있는 것이다.** 이런 이유 때문에 parallel을 잘못 사용할 경우 순차적 실행보다 더 느릴 수도 있다.

병렬 처리는 간단한 작업도 쉽지 않아 보이는군요

**Comment by hyuunnn** [comment]
그러게요.. 생각해보니 `reduce`도 이전에 저장된 값을 토대로 누적 계산되는 형태인데, 병렬로 동작했을 때 문제가 될 수 있는 부분들을 내부에서 처리해주는 듯하네요..
