### ISSUE TITLE
[Chapter 07] 가비지 컬렉터

### ISSUE THREAD

**Issue by xet-a** [Java-Spring-Study/modern-java-in-action#6]
`p.247 병렬 스트림 벤치마크 실행 예제`에서 가비지 컬렉터로 인한 오버헤드를 줄이기 위해 Heap 크기를 충분하게 설정하고, 매 벤치마크 실행 후 가비지 컬렉터를 동작하도록 합니다. 왜 그렇게 설정하는지, 가비지 컬렉터가 벤치마크 실행에 어떻게 영향을 미치는지 궁금합니다.

**Comment by xet-a** [comment]
아래는 간단하게 정리한 가비지 컬렉터의 동작 내용입니다.

- Garbage Collector는 주기적으로 JVM의 Heap(동적 할당 메모리 영역)을 점검하여
Stack에서 참조되지 않는 객체를 메모리에서 해제하는 역할을 함 (Heap 영역을 가리키는 참조 변수가 Stack에 할당됨)
- Garbage Collector 과정: **Mark and Sweep**

   - **Mark**
 GC가 Stack의 모든 변수를 스캔하면서 각각 어떤 객체를 참조하고 있는지 찾아서 마킹하고,
Reachable 객체(유효한 참조가 존재하는 객체)가 참조하고 있는 객체도 찾아서 마킹함
  - **Sweep**
마킹되지 않은 객체를 Heap에서 제거함
    
- Java9부터 처리속도가 빠른 G1 GC를 기본 가비지 컬렉터(Default Garbage Collector) 사용

cc) https://mangkyu.tistory.com/119
https://youtu.be/vZRmCbl871I

**Comment by JJimini** [comment]
문장을 두 가지로 나눌 수 있을 것 같습니다.

1. 벤치마크가 가비지 컬렉터(GC)의 영향을 받지 않도록 힙의 크기를 충분히 설정했다.
=> GC의 단점으로 메모리가 언제 해제되는지 정확하게 알 수 없고, GC가 동작하는 동안에는 JVM의 다른 동작을 멈추기 때문에 오버헤드가 발생하게 됩니다. 이로 인해서 GC가 너무 자주 실행되면 소프트웨어 성능이 하락합니다. 따라서 가비지 컬렉터가 최대한 동작하지 않도록 하기 위해 힙의 크기를 충분히 설정합니다.

2. 벤치마크가 끝날 때마다 가비지 컬렉터가 실행되도록 강제했다.
=> 벤치마크가 끝나면 GC를 강제로 실행하여(System.gc()) 더 이상 사용하지 않는 메모리 영역을 알아서 해제시켜 더 신뢰할 만한 결과를 도출합니다. (해당 예시 코드에서 벤치마크를 2번 시행하기 때문에)

추가적으로 System.gc()와 같이 메소드를 직접 호출해도 실제 가비지 컬렉터가 작동할지는 미지수입니다. 그래서 여전히 도출되는 결과는 정확하지 않을 수 있습니다.

**Comment by hyuunnn** [comment]
도움이 될지 모르겠지만 GC 관련 책들입니다..!
http://www.yes24.com/Product/Goods/51095692
http://www.yes24.com/Product/Goods/11261731
